overwrite: true
schema: http://localhost:4000/graphql
documents: src/graphql/**/*.{ts,tsx}
generates:
  src/generated/introspection-result.ts:
    plugins:
      - fragment-matcher
  src/generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHOC: false
      withComponent: false
      withHooks: true
      maybeValue: T | undefined
      skipTypename: true
